# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.classification_policy import ClassificationPolicy
from .models.classification_result import ClassificationResult
from .models.classification_result_collection import ClassificationResultCollection
from .models.content_match import ContentMatch
from .models.error_response import ErrorResponse
from .models.rule_match import RuleMatch
from .models.tag import Tag
from .models.tag_property import TagProperty

# import apis into sdk package
from .apis.veritas_information_classifier_vic_api import VeritasInformationClassifierVICApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
