# coding: utf-8

"""
    Veritas Information Classifier (VIC)

    APIs

    OpenAPI spec version: Resource Specific
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClassificationPolicy(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, policy_id=None, tags=None, policy_hash=None):
        """
        ClassificationPolicy - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'policy_id': 'str',
            'tags': 'list[str]',
            'policy_hash': 'str'
        }

        self.attribute_map = {
            'policy_id': 'policyId',
            'tags': 'tags',
            'policy_hash': 'policyHash'
        }

        self._policy_id = policy_id
        self._tags = tags
        self._policy_hash = policy_hash

    @property
    def policy_id(self):
        """
        Gets the policy_id of this ClassificationPolicy.

        :return: The policy_id of this ClassificationPolicy.
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id):
        """
        Sets the policy_id of this ClassificationPolicy.

        :param policy_id: The policy_id of this ClassificationPolicy.
        :type: str
        """

        self._policy_id = policy_id

    @property
    def tags(self):
        """
        Gets the tags of this ClassificationPolicy.

        :return: The tags of this ClassificationPolicy.
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this ClassificationPolicy.

        :param tags: The tags of this ClassificationPolicy.
        :type: list[str]
        """

        self._tags = tags

    @property
    def policy_hash(self):
        """
        Gets the policy_hash of this ClassificationPolicy.
        A hash of the policy body and any associated custom patterns.  This can be used to track significant changes to the policy that may warrant re-classification of documents.  Note that built-in pattern bodies are NOT included in the hash, as they are not expected to change significantly over time.

        :return: The policy_hash of this ClassificationPolicy.
        :rtype: str
        """
        return self._policy_hash

    @policy_hash.setter
    def policy_hash(self, policy_hash):
        """
        Sets the policy_hash of this ClassificationPolicy.
        A hash of the policy body and any associated custom patterns.  This can be used to track significant changes to the policy that may warrant re-classification of documents.  Note that built-in pattern bodies are NOT included in the hash, as they are not expected to change significantly over time.

        :param policy_hash: The policy_hash of this ClassificationPolicy.
        :type: str
        """

        self._policy_hash = policy_hash

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClassificationPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
